# Generated by Django 5.0.2 on 2024-02-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='images',
            new_name='image',
        ),
    ]
