# Generated by Django 5.0.2 on 2024-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_rename_images_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Глубина "см"'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Высота "см"'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ширина "см"'),
        ),
    ]
