# Generated by Django 5.0.2 on 2024-02-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0008_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
