# Generated by Django 5.0.2 on 2024-02-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0009_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.order')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
