# Generated by Django 5.0.2 on 2024-02-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0010_orderhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='orders',
            new_name='order',
        ),
    ]
