# Generated by Django 5.0.2 on 2024-02-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0013_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
